name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -race -failfast -timeout 1m ./...
