name: Go
on: [push, pull_request]
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.17
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: go test -race -shuffle on -timeout 1m -coverprofile=covprofile ./...
      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: covprofile
